"""Shared app aliases for legacy desktop intent compatibility."""

from __future__ import annotations

import re


APP_ALIASES: dict[str, str] = {
    "applemusic": "Music",
    "苹果音乐": "Music",
    "music": "Music",
    "音乐": "Music",
    "qq音乐": "QQ音乐",
    "qqmusic": "QQ音乐",
    "网易云": "网易云音乐",
    "网易云音乐": "网易云音乐",
    "neteasecloud": "网易云音乐",
    "neteasecloudmusic": "网易云音乐",
    "neteasemusic": "网易云音乐",
    "cloudmusic": "网易云音乐",
    "googlechrome": "Google Chrome",
    "chrome": "Google Chrome",
    "chrome浏览器": "Google Chrome",
    "谷歌浏览器": "Google Chrome",
    "浏览器": "Google Chrome",
    "默认浏览器": "Google Chrome",
    "系统默认浏览器": "Google Chrome",
    "默认网页浏览器": "Google Chrome",
    "defaultbrowser": "Google Chrome",
    "defaultwebbrowser": "Google Chrome",
    "browser": "Google Chrome",
    "safari": "Safari",
    "finder": "Finder",
    "访达": "Finder",
    "terminal": "Terminal",
    "终端": "Terminal",
    "命令行": "Terminal",
    "systemsettings": "System Settings",
    "systempreferences": "System Settings",
    "settings": "System Settings",
    "系统设置": "System Settings",
    "系统偏好": "System Settings",
    "系统偏好设置": "System Settings",
    "设置": "System Settings",
    "蓝牙设置": "System Settings",
    "bluetoothsettings": "System Settings",
    "wifi设置": "System Settings",
    "wi-fi设置": "System Settings",
    "wifisettings": "System Settings",
    "wi-fisettings": "System Settings",
    "无线网络设置": "System Settings",
    "网络设置": "System Settings",
    "声音设置": "System Settings",
    "音量设置": "System Settings",
    "显示器设置": "System Settings",
    "显示设置": "System Settings",
    "folder": "Finder",
    "folders": "Finder",
    "afolder": "Finder",
    "directory": "Finder",
    "directories": "Finder",
    "文件夹": "Finder",
    "目录": "Finder",
    "文件管理器": "Finder",
    "文件浏览器": "Finder",
    "notes": "Notes",
    "备忘录": "Notes",
    "calendar": "Calendar",
    "日历": "Calendar",
    "reminders": "Reminders",
    "提醒事项": "Reminders",
    "mail": "Mail",
    "邮件": "Mail",
    "邮箱": "Mail",
    "电子邮件": "Mail",
    "messages": "Messages",
    "信息": "Messages",
    "短信": "Messages",
    "通讯": "Messages",
    "facetime": "FaceTime",
    "contacts": "Contacts",
    "联系人": "Contacts",
    "通讯录": "Contacts",
    "maps": "Maps",
    "地图": "Maps",
    "photos": "Photos",
    "照片": "Photos",
    "preview": "Preview",
    "预览": "Preview",
    "图片查看器": "Preview",
    "图像查看器": "Preview",
    "calculator": "Calculator",
    "计算器": "Calculator",
    "appstore": "App Store",
    "应用商店": "App Store",
    "activitymonitor": "Activity Monitor",
    "活动监视器": "Activity Monitor",
    "系统活动监视器": "Activity Monitor",
    "diskutility": "Disk Utility",
    "磁盘工具": "Disk Utility",
    "磁盘工具程序": "Disk Utility",
    "console": "Console",
    "控制台": "Console",
    "fontbook": "Font Book",
    "字体册": "Font Book",
    "字体簿": "Font Book",
    "systeminformation": "System Information",
    "系统信息": "System Information",
    "scripteditor": "Script Editor",
    "脚本编辑器": "Script Editor",
    "automator": "Automator",
    "自动操作": "Automator",
    "自动操作程序": "Automator",
    "voicememos": "Voice Memos",
    "语音备忘录": "Voice Memos",
    "stickies": "Stickies",
    "便笺": "Stickies",
    "dictionary": "Dictionary",
    "词典": "Dictionary",
    "digitalcolormeter": "Digital Color Meter",
    "数码测色计": "Digital Color Meter",
    "audiomidisetup": "Audio MIDI Setup",
    "音频midi设置": "Audio MIDI Setup",
    "colorsyncutility": "ColorSync Utility",
    "色彩同步实用工具": "ColorSync Utility",
    "migrationassistant": "Migration Assistant",
    "迁移助理": "Migration Assistant",
    "timemachine": "Time Machine",
    "时间机器": "Time Machine",
    "launchpad": "Launchpad",
    "启动台": "Launchpad",
    "controlcenter": "Control Center",
    "控制中心": "Control Center",
    "notificationcenter": "Notification Center",
    "通知中心": "Notification Center",
    "keychainaccess": "Keychain Access",
    "钥匙串": "Keychain Access",
    "钥匙串访问": "Keychain Access",
    "textedit": "TextEdit",
    "文本编辑": "TextEdit",
    "quicktime": "QuickTime Player",
    "quicktimeplayer": "QuickTime Player",
    "wechat": "WeChat",
    "微信": "WeChat",
    "qq": "QQ",
    "slack": "Slack",
    "discord": "Discord",
    "notion": "Notion",
    "obsidian": "Obsidian",
    "chatgpt": "ChatGPT",
    "chatgpt客户端": "ChatGPT",
    "claude": "Claude",
    "vscode": "Visual Studio Code",
    "vsc": "Visual Studio Code",
    "visualstudiocode": "Visual Studio Code",
    "code": "Visual Studio Code",
    "cursor": "Cursor",
    "arc": "Arc",
    "arc浏览器": "Arc",
    "firefox": "Firefox",
    "火狐": "Firefox",
    "firefox浏览器": "Firefox",
    "火狐浏览器": "Firefox",
    "edge": "Microsoft Edge",
    "edge浏览器": "Microsoft Edge",
    "microsoftedge": "Microsoft Edge",
    "brave": "Brave Browser",
    "brave浏览器": "Brave Browser",
    "spotify": "Spotify",
    "音乐播放器": "Music",
    "播放器": "Music",
    "musicplayer": "Music",
    "shortcuts": "Shortcuts",
    "快捷指令": "Shortcuts",
    "figma": "Figma",
    "zoom": "zoom.us",
    "zoomus": "zoom.us",
    "teams": "Microsoft Teams",
    "microsoftteams": "Microsoft Teams",
    "word": "Microsoft Word",
    "microsoftword": "Microsoft Word",
    "excel": "Microsoft Excel",
    "microsoftexcel": "Microsoft Excel",
    "powerpoint": "Microsoft PowerPoint",
    "ppt": "Microsoft PowerPoint",
    "microsoftpowerpoint": "Microsoft PowerPoint",
    "outlook": "Microsoft Outlook",
    "microsoftoutlook": "Microsoft Outlook",
    "telegram": "Telegram",
    "telegramdesktop": "Telegram",
    "whatsapp": "WhatsApp",
    "企业微信": "WeCom",
    "企业微信客户端": "WeCom",
    "wecom": "WeCom",
    "wecomclient": "WeCom",
    "wechatwork": "WeCom",
    "飞书": "飞书",
    "feishu": "Feishu",
    "lark": "Lark",
    "钉钉": "DingTalk",
    "dingtalk": "DingTalk",
    "腾讯会议": "Tencent Meeting",
    "tencentmeeting": "Tencent Meeting",
    "iterm": "iTerm",
    "iterm2": "iTerm",
    "warp": "Warp",
    "docker": "Docker",
    "xcode": "Xcode",
    "postman": "Postman",
    "linear": "Linear",
    "raycast": "Raycast",
    "pycharm": "PyCharm",
    "intellij": "IntelliJ IDEA",
    "idea": "IntelliJ IDEA",
    "webstorm": "WebStorm",
    "goland": "GoLand",
}


# Generic labels describe an app role chosen by the user or operating system;
# they are aliases for planning convenience, not stable installed-app identity.
GENERIC_APP_ALIAS_COMPACTS = frozenset(
    {
        "browser",
        "defaultbrowser",
        "systemdefaultbrowser",
        "defaultwebbrowser",
        "webbrowser",
        "浏览器",
        "默认浏览器",
        "系统默认浏览器",
        "默认网页浏览器",
        "文件管理器",
        "文件浏览器",
        "terminal",
        "终端",
        "命令行",
        "musicplayer",
        "音乐播放器",
        "播放器",
    }
)

BROWSER_APP_NAMES = {
    "Arc",
    "Brave Browser",
    "Firefox",
    "Google Chrome",
    "Microsoft Edge",
    "Safari",
}

BROWSER_INTERNAL_PAGE_SCHEMES = {
    "Brave Browser": "brave",
    "Google Chrome": "chrome",
    "Microsoft Edge": "edge",
}

BROWSER_INTERNAL_PAGE_PATHS = {
    "downloads": "downloads",
    "bookmarks": "bookmarks",
    "extensions": "extensions",
}

COMMUNICATION_APP_NAMES = {
    "DingTalk",
    "Feishu",
    "Lark",
    "Messages",
    "QQ",
    "Slack",
    "Telegram",
    "WeChat",
    "WhatsApp",
}

EMAIL_APP_NAMES = {
    "Mail",
    "Microsoft Outlook",
}


def compact_app_alias(value: str) -> str:
    return re.sub(r"[\s._-]+", "", str(value or "").strip().lower())


def known_app_followup_aliases() -> list[tuple[str, str]]:
    candidates: dict[str, str] = {}
    for alias, app_name in APP_ALIASES.items():
        candidates.setdefault(alias, app_name)
    for app_name in set(APP_ALIASES.values()):
        candidates.setdefault(app_name, app_name)
    return sorted(
        candidates.items(),
        key=lambda item: len(compact_app_alias(item[0])),
        reverse=True,
    )
